/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package media6007;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        System.out.println("Testing...");
        assertEquals(1, 1);
        // Main classUnderTest = new Main();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
