/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package media6007;

public class Main {

    public static void main(String[] args) {
        System.out.println("Hello from Main");
    }
}
